In [3]:
import numpy as np
class Perceptron(object):
    """
    感知器类，表示单个神经元
    eta : 感知器学习率
    n_iter : 迭代次数
    w_ : 权重向量数组
    errors_ : 错误次数数组, 用于记录神经元判断错误次数
    """
    
    def __init__(self, eta = 0.01, n_iter = 10) :
        '''构造函数'''
        self.eta = eta
        self.n_iter = n_iter
        pass
    
    def fit(self, X, y):
        """
        输入训练数据，培训神经元
        X： 输入数据样本
        y： 输入数据样本的对应分类
        X: shape[n.samples, n_features] numpy中的函数，表示多维数组的属性
        eg :
        X: [[1,2,3], [4,5,6]]
        n_samples : 2, n_feature : 3
        y : [1, -1]
        """
        
        '''初始化基本数据'''
        self.w_  = np.zeros(1+X.shape[1]) # 加1是为w0, 表示阈值
        self.errors_ = [] # 初始化为数组
        
        '''开始训练'''
        for i in range(self.n_iter) :
            errors = 0
            for xi, target in zip(X,y) : # 每一行样本数据以及它的分类
                '''
                输入样本数据
                xi : 样本数据行
                y : 样本数据对应分类
                '''
                z = self.net_input(xi)
                '''激活函数'''
                _y = self.predict(z)
                '''调整权重向量'''
                update = self.eta * (target - _y)
                self.w_[1:] += update * xi # w[i] = eta * (y - _y) * xi
                self.w_[0] = update
                errors += int(update != 0.0)
                pass
            self.errors_.append(errors)
            pass
        pass

    def net_input(self, X) :
        '''每一行样本数据输入得到输出结果'''
        return np.dot(X, self.w_[1:]) + self.w_[0]
        pass
    
    def predict(self, z):
        '''激活函数'''
        return np.where(z >= 0.0, 1, -1)
        pass
    
    pass


In [6]:
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

def plot_decision_region(X, y, classifier, resolution=0.2):
    markers = ('s','x','o','v')
    colors = ('red', 'blue', 'lightgreen', 'gray', 'cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))])
    x_min,x_max = X[:,0].min(),X[:,0].max()
    y_min,y_max = X[:,1].min(),X[:,1].max()
    print(x_min, x_max)
    print(y_min, y_max)
    # 扩展成一个二维向量
    xx1, xx2 = np.meshgrid(np.arange(x_min, x_max,resolution), 
                           np.arange(y_min, y_max,resolution))
    print(xx1.shape, xx1)
    print(xx2.shape, xx2)
    # 预测
    z = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    print("分类结果 ", z.shape)
    z = z.reshape(xx1.shape)
    plt.contourf(xx1, xx2, z, alpha=0.4, cmap=cmap)
    plt.xlim(xx1.min(), xx1.max())
    plt.ylim(xx2.min(), xx2.max())
    for idx, cl in enumerate(np.unique(y)):
#         plt.scatter(x=X[y == cl, 0], y=X[y==cl, 1], alpha=0.8, c=cmap(idx), marker=markers[idx], label=cl)
        pass
    pass

# 读取文件，并将数据可视化处理
file = "/home/gt/Documents/dataset/iris/iris.data"
df = pd.read_csv(file, header = None)
# df.head(10)

# 抽取前100行数据的第4列
y = df.loc[0:100, 4].values
# 将字符串转换成int数字
y = np.where(y == 'Iris-setosa', 1, -1)
# print(y.shape)

# 抽取前100行数据的第0列和第2列作为输入数据
X = df.iloc[0:100, [0, 2]].values
# print(X.shape)
# 画出X
# plt.scatter(X[:50, 0], X[:50, 1], color='red', marker='o', label='setosa')
# plt.scatter(X[50:100, 0], X[50:100, 1], color="blue", marker="x", label="versicolor")
# plt.xlabel("花瓣长度")
# plt.ylabel("花径长度")
# plt.legend("upper left")

# 将样本数据输入感知器
ppn = Perceptron(eta = 0.1, n_iter = 10)
ppn.fit(X, y) # 训练
# plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_,marker="o") #　绘制出错曲线
# plt.show() 

plot_decision_region(X,y,ppn,resolution=0.02)
plt.xlabel("花径长度")
plt.ylabel("花瓣长度")
plt.legend("upper left")
plt.show()

    

4.3 7.0
1.0 5.1
(205, 135) [[4.3  4.32 4.34 ... 6.94 6.96 6.98]
 [4.3  4.32 4.34 ... 6.94 6.96 6.98]
 [4.3  4.32 4.34 ... 6.94 6.96 6.98]
 ...
 [4.3  4.32 4.34 ... 6.94 6.96 6.98]
 [4.3  4.32 4.34 ... 6.94 6.96 6.98]
 [4.3  4.32 4.34 ... 6.94 6.96 6.98]]
(205, 135) [[1.   1.   1.   ... 1.   1.   1.  ]
 [1.02 1.02 1.02 ... 1.02 1.02 1.02]
 [1.04 1.04 1.04 ... 1.04 1.04 1.04]
 ...
 [5.04 5.04 5.04 ... 5.04 5.04 5.04]
 [5.06 5.06 5.06 ... 5.06 5.06 5.06]
 [5.08 5.08 5.08 ... 5.08 5.08 5.08]]
分类结果  (27675, 2)


ValueError: cannot reshape array of size 55350 into shape (205,135)